In [2]:
import numpy as np

arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr1 * arr1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [4]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [5]:
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])

In [6]:
arr1 ** 3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]])

In [7]:
############# Index
arange = np.arange(0, 11)
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
slice_arr = arange[1:5]
slice_arr

array([1, 2, 3, 4])

In [9]:
slice_arr[:] = 99
slice_arr

array([99, 99, 99, 99])

In [10]:
arange[0: 5] = 100
arange

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
############### Copy
arr_copy = arange.copy()
arr_copy[:] = 1
arr_copy

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
arange

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
############### 2-D
arr_2d = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
############ Array Tansposition
arr = np.arange(50).reshape((10, 5))
arr

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [15]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [16]:
np.dot(arr.T, arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [17]:
arr3d = np.arange(50).reshape((5, 5, 2))
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [18]:
arr3d.transpose((1, 0, 2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [19]:
arr = np.array([[1, 2, 3]])
arr

array([[1, 2, 3]])

In [20]:
arr.swapaxes(0, 1)

array([[1],
       [2],
       [3]])

In [21]:
############# Universal array function
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [23]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [24]:
### Binary function
A = np.random.randn(10)
A

array([ 1.23103134, -0.71718531, -1.05713428,  1.35145759,  0.31926948,
       -0.48338047, -1.18220929, -0.22175203, -1.14155243, -0.16603255])

In [25]:
B = np.random.randn(10)
B

array([ 1.13569766, -1.09095561,  1.52978704, -1.83059485,  0.33391689,
        0.15722522, -1.39356881, -1.22131533, -0.689223  ,  0.11346654])

In [26]:
np.add(A, B)

array([ 2.366729  , -1.80814092,  0.47265275, -0.47913726,  0.65318637,
       -0.32615526, -2.5757781 , -1.44306736, -1.83077543, -0.05256601])

In [27]:
np.maximum(A, B)

array([ 1.23103134, -0.71718531,  1.52978704,  1.35145759,  0.33391689,
        0.15722522, -1.18220929, -0.22175203, -0.689223  ,  0.11346654])