In [40]:
import numpy as np

In [41]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [42]:
np.save('myarray', arr)


In [43]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [45]:
arr1 = np.load('myarray.npy')
arr1


array([0, 1, 2, 3, 4])

In [46]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.savez('ziparray.npz', x=arr1, y=arr2)

In [48]:
arc_arr = np.load('ziparray.npz')
arc_arr['x']


array([0, 1, 2, 3, 4])

In [49]:
arc_arr['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.savetxt('mytxtarr.txt', arr, delimiter='|')

In [52]:
arr = np.loadtxt('mytxtarr.txt', delimiter='|')
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])