In [2]:
import numpy as np


my_list1 = [1, 2, 3, 4]
my_array1 = np.array(my_list1)
my_array1

ImportError: No module named 'numpy'

In [2]:
my_list2 = [5, 6, 7, 8]
my_lists = [my_list1, my_list2]
my_array2 = np.array(my_lists)
my_array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
my_zeros_array = np.zeros(5)
my_zeros_array

NameError: name 'np' is not defined

In [4]:
my_ones = np.ones([5, 5])
my_ones

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [5]:
my_empty = np.empty(5, float)
my_empty

array([  0.00000000e+000,   2.10877889e-316,   6.92189469e-310,
         6.92190725e-310,   2.37151510e-322])

In [6]:
my_eye = np.eye(5)
my_eye

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [7]:
my_arange = np.arange(5)
my_arange

array([0, 1, 2, 3, 4])

In [8]:
my_arange2 = np.arange(5, 50, 3)
my_arange2

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])