In [7]:
import numpy as np

In [8]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [9]:
np.save('files/myarray', arr)


In [10]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.load('files/myarray.npy')

array([0, 1, 2, 3, 4])

In [12]:
arr1 = np.load('files/myarray.npy')
arr1


array([0, 1, 2, 3, 4])

In [13]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.savez('files/ziparray.npz', x=arr1, y=arr2)

In [15]:
arc_arr = np.load('files/ziparray.npz')
arc_arr['x']


array([0, 1, 2, 3, 4])

In [16]:
arc_arr['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.savetxt('files/mytxtarr.txt', arr, delimiter='|')

In [19]:
arr = np.loadtxt('files/mytxtarr.txt', delimiter='|')
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])